# Generated by Django 4.0 on 2024-06-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopost',
            name='nice',
            field=models.IntegerField(default=0),
        ),
    ]
